/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SearchApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SearchApiTests
    {
        private SearchApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SearchApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SearchApi
            //Assert.IsInstanceOfType(typeof(SearchApi), instance, "instance is a SearchApi");
        }

        /// <summary>
        /// Test SearchLyrics
        /// </summary>
        [Test]
        public void SearchLyricsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string q = null;
            //int? limit = null;
            //int? offset = null;
            //var response = instance.SearchLyrics(q, limit, offset);
            //Assert.IsInstanceOf<LyricsListResponse> (response, "response is LyricsListResponse");
        }
        /// <summary>
        /// Test SearchLyricsByArtist
        /// </summary>
        [Test]
        public void SearchLyricsByArtistTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string artist = null;
            //int? limit = null;
            //int? offset = null;
            //var response = instance.SearchLyricsByArtist(artist, limit, offset);
            //Assert.IsInstanceOf<LyricsListResponse> (response, "response is LyricsListResponse");
        }
        /// <summary>
        /// Test SearchLyricsByTitle
        /// </summary>
        [Test]
        public void SearchLyricsByTitleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string title = null;
            //int? limit = null;
            //int? offset = null;
            //var response = instance.SearchLyricsByTitle(title, limit, offset);
            //Assert.IsInstanceOf<LyricsListResponse> (response, "response is LyricsListResponse");
        }
    }

}
