/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VotingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class VotingApiTests
    {
        private VotingApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new VotingApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VotingApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' VotingApi
            //Assert.IsInstanceOfType(typeof(VotingApi), instance, "instance is a VotingApi");
        }

        /// <summary>
        /// Test VoteForLyric
        /// </summary>
        [Test]
        public void VoteForLyricTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //VoteRequest body = null;
            //var response = instance.VoteForLyric(body);
            //Assert.IsInstanceOf<SuccessResponse> (response, "response is SuccessResponse");
        }
        /// <summary>
        /// Test VoteForTranslatedLyric
        /// </summary>
        [Test]
        public void VoteForTranslatedLyricTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //VoteRequest body = null;
            //var response = instance.VoteForTranslatedLyric(body);
            //Assert.IsInstanceOf<SuccessResponse> (response, "response is SuccessResponse");
        }
    }

}
