/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using SimpMusic.Lyrics.Client;
using SimpMusic.Lyrics.Client.Model;

namespace SimpMusic.Lyrics.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ILyricsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create New Lyric
        /// </summary>
        /// <remarks>
        /// Creates a new lyric entry with the provided lyric data. Requires HMAC authentication.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>CreateLyricResponse</returns>
        CreateLyricResponse CreateLyric (CreateLyricRequest body);

        /// <summary>
        /// Create New Lyric
        /// </summary>
        /// <remarks>
        /// Creates a new lyric entry with the provided lyric data. Requires HMAC authentication.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of CreateLyricResponse</returns>
        ApiResponse<CreateLyricResponse> CreateLyricWithHttpInfo (CreateLyricRequest body);
        /// <summary>
        /// Get Lyrics by Video ID
        /// </summary>
        /// <remarks>
        /// Fetches lyrics associated with a specific video ID. Optionally supports pagination with limit and offset.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>LyricsResponse</returns>
        LyricsResponse GetLyricsByVideoId (string videoId, int? limit = null, int? offset = null);

        /// <summary>
        /// Get Lyrics by Video ID
        /// </summary>
        /// <remarks>
        /// Fetches lyrics associated with a specific video ID. Optionally supports pagination with limit and offset.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>ApiResponse of LyricsResponse</returns>
        ApiResponse<LyricsResponse> GetLyricsByVideoIdWithHttpInfo (string videoId, int? limit = null, int? offset = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create New Lyric
        /// </summary>
        /// <remarks>
        /// Creates a new lyric entry with the provided lyric data. Requires HMAC authentication.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of CreateLyricResponse</returns>
        System.Threading.Tasks.Task<CreateLyricResponse> CreateLyricAsync (CreateLyricRequest body);

        /// <summary>
        /// Create New Lyric
        /// </summary>
        /// <remarks>
        /// Creates a new lyric entry with the provided lyric data. Requires HMAC authentication.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (CreateLyricResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateLyricResponse>> CreateLyricAsyncWithHttpInfo (CreateLyricRequest body);
        /// <summary>
        /// Get Lyrics by Video ID
        /// </summary>
        /// <remarks>
        /// Fetches lyrics associated with a specific video ID. Optionally supports pagination with limit and offset.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of LyricsResponse</returns>
        System.Threading.Tasks.Task<LyricsResponse> GetLyricsByVideoIdAsync (string videoId, int? limit = null, int? offset = null);

        /// <summary>
        /// Get Lyrics by Video ID
        /// </summary>
        /// <remarks>
        /// Fetches lyrics associated with a specific video ID. Optionally supports pagination with limit and offset.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of ApiResponse (LyricsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LyricsResponse>> GetLyricsByVideoIdAsyncWithHttpInfo (string videoId, int? limit = null, int? offset = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class LyricsApi : ILyricsApi
    {
        private SimpMusic.Lyrics.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LyricsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LyricsApi(String basePath)
        {
            this.Configuration = new SimpMusic.Lyrics.Client.Configuration { BasePath = basePath };

            ExceptionFactory = SimpMusic.Lyrics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LyricsApi"/> class
        /// </summary>
        /// <returns></returns>
        public LyricsApi()
        {
            this.Configuration = SimpMusic.Lyrics.Client.Configuration.Default;

            ExceptionFactory = SimpMusic.Lyrics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LyricsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LyricsApi(SimpMusic.Lyrics.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = SimpMusic.Lyrics.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = SimpMusic.Lyrics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SimpMusic.Lyrics.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SimpMusic.Lyrics.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create New Lyric Creates a new lyric entry with the provided lyric data. Requires HMAC authentication.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>CreateLyricResponse</returns>
        public CreateLyricResponse CreateLyric (CreateLyricRequest body)
        {
             ApiResponse<CreateLyricResponse> localVarResponse = CreateLyricWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create New Lyric Creates a new lyric entry with the provided lyric data. Requires HMAC authentication.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of CreateLyricResponse</returns>
        public ApiResponse< CreateLyricResponse > CreateLyricWithHttpInfo (CreateLyricRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling LyricsApi->CreateLyric");

            var localVarPath = "/v1";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (hmacAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-HMAC")))
            {
                localVarHeaderParams["X-HMAC"] = this.Configuration.GetApiKeyWithPrefix("X-HMAC");
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateLyric", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateLyricResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateLyricResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateLyricResponse)));
        }

        /// <summary>
        /// Create New Lyric Creates a new lyric entry with the provided lyric data. Requires HMAC authentication.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of CreateLyricResponse</returns>
        public async System.Threading.Tasks.Task<CreateLyricResponse> CreateLyricAsync (CreateLyricRequest body)
        {
             ApiResponse<CreateLyricResponse> localVarResponse = await CreateLyricAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create New Lyric Creates a new lyric entry with the provided lyric data. Requires HMAC authentication.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (CreateLyricResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreateLyricResponse>> CreateLyricAsyncWithHttpInfo (CreateLyricRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling LyricsApi->CreateLyric");

            var localVarPath = "/v1";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (hmacAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-HMAC")))
            {
                localVarHeaderParams["X-HMAC"] = this.Configuration.GetApiKeyWithPrefix("X-HMAC");
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateLyric", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateLyricResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateLyricResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateLyricResponse)));
        }

        /// <summary>
        /// Get Lyrics by Video ID Fetches lyrics associated with a specific video ID. Optionally supports pagination with limit and offset.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>LyricsResponse</returns>
        public LyricsResponse GetLyricsByVideoId (string videoId, int? limit = null, int? offset = null)
        {
             ApiResponse<LyricsResponse> localVarResponse = GetLyricsByVideoIdWithHttpInfo(videoId, limit, offset);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Lyrics by Video ID Fetches lyrics associated with a specific video ID. Optionally supports pagination with limit and offset.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>ApiResponse of LyricsResponse</returns>
        public ApiResponse< LyricsResponse > GetLyricsByVideoIdWithHttpInfo (string videoId, int? limit = null, int? offset = null)
        {
            // verify the required parameter 'videoId' is set
            if (videoId == null)
                throw new ApiException(400, "Missing required parameter 'videoId' when calling LyricsApi->GetLyricsByVideoId");

            var localVarPath = "/v1/{videoId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (videoId != null) localVarPathParams.Add("videoId", this.Configuration.ApiClient.ParameterToString(videoId)); // path parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetLyricsByVideoId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LyricsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (LyricsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LyricsResponse)));
        }

        /// <summary>
        /// Get Lyrics by Video ID Fetches lyrics associated with a specific video ID. Optionally supports pagination with limit and offset.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of LyricsResponse</returns>
        public async System.Threading.Tasks.Task<LyricsResponse> GetLyricsByVideoIdAsync (string videoId, int? limit = null, int? offset = null)
        {
             ApiResponse<LyricsResponse> localVarResponse = await GetLyricsByVideoIdAsyncWithHttpInfo(videoId, limit, offset);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Lyrics by Video ID Fetches lyrics associated with a specific video ID. Optionally supports pagination with limit and offset.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of ApiResponse (LyricsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LyricsResponse>> GetLyricsByVideoIdAsyncWithHttpInfo (string videoId, int? limit = null, int? offset = null)
        {
            // verify the required parameter 'videoId' is set
            if (videoId == null)
                throw new ApiException(400, "Missing required parameter 'videoId' when calling LyricsApi->GetLyricsByVideoId");

            var localVarPath = "/v1/{videoId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (videoId != null) localVarPathParams.Add("videoId", this.Configuration.ApiClient.ParameterToString(videoId)); // path parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetLyricsByVideoId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LyricsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (LyricsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LyricsResponse)));
        }

    }
}
