/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using SimpMusic.Lyrics.Client;
using SimpMusic.Lyrics.Client.Model;

namespace SimpMusic.Lyrics.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ITranslationsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Translated Lyric
        /// </summary>
        /// <remarks>
        /// Creates a new translated lyric entry. Requires HMAC authentication.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>CreateTranslatedLyricResponse</returns>
        CreateTranslatedLyricResponse CreateTranslatedLyric (CreateTranslatedLyricRequest body);

        /// <summary>
        /// Create Translated Lyric
        /// </summary>
        /// <remarks>
        /// Creates a new translated lyric entry. Requires HMAC authentication.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of CreateTranslatedLyricResponse</returns>
        ApiResponse<CreateTranslatedLyricResponse> CreateTranslatedLyricWithHttpInfo (CreateTranslatedLyricRequest body);
        /// <summary>
        /// Get Translated Lyrics by Video ID
        /// </summary>
        /// <remarks>
        /// Fetches translated lyrics for a specific video ID with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>TranslatedLyricsListResponse</returns>
        TranslatedLyricsListResponse GetTranslatedLyricsByVideoId (string videoId, int? limit = null, int? offset = null);

        /// <summary>
        /// Get Translated Lyrics by Video ID
        /// </summary>
        /// <remarks>
        /// Fetches translated lyrics for a specific video ID with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>ApiResponse of TranslatedLyricsListResponse</returns>
        ApiResponse<TranslatedLyricsListResponse> GetTranslatedLyricsByVideoIdWithHttpInfo (string videoId, int? limit = null, int? offset = null);
        /// <summary>
        /// Get Translated Lyrics by Video ID and Language
        /// </summary>
        /// <remarks>
        /// Fetches translated lyrics for a specific video ID and language code.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="language">Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;, &#x27;de&#x27;, &#x27;ja&#x27;)</param>
        /// <returns>TranslatedLyricsListResponse</returns>
        TranslatedLyricsListResponse GetTranslatedLyricsByVideoIdAndLanguage (string videoId, string language);

        /// <summary>
        /// Get Translated Lyrics by Video ID and Language
        /// </summary>
        /// <remarks>
        /// Fetches translated lyrics for a specific video ID and language code.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="language">Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;, &#x27;de&#x27;, &#x27;ja&#x27;)</param>
        /// <returns>ApiResponse of TranslatedLyricsListResponse</returns>
        ApiResponse<TranslatedLyricsListResponse> GetTranslatedLyricsByVideoIdAndLanguageWithHttpInfo (string videoId, string language);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create Translated Lyric
        /// </summary>
        /// <remarks>
        /// Creates a new translated lyric entry. Requires HMAC authentication.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of CreateTranslatedLyricResponse</returns>
        System.Threading.Tasks.Task<CreateTranslatedLyricResponse> CreateTranslatedLyricAsync (CreateTranslatedLyricRequest body);

        /// <summary>
        /// Create Translated Lyric
        /// </summary>
        /// <remarks>
        /// Creates a new translated lyric entry. Requires HMAC authentication.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (CreateTranslatedLyricResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateTranslatedLyricResponse>> CreateTranslatedLyricAsyncWithHttpInfo (CreateTranslatedLyricRequest body);
        /// <summary>
        /// Get Translated Lyrics by Video ID
        /// </summary>
        /// <remarks>
        /// Fetches translated lyrics for a specific video ID with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of TranslatedLyricsListResponse</returns>
        System.Threading.Tasks.Task<TranslatedLyricsListResponse> GetTranslatedLyricsByVideoIdAsync (string videoId, int? limit = null, int? offset = null);

        /// <summary>
        /// Get Translated Lyrics by Video ID
        /// </summary>
        /// <remarks>
        /// Fetches translated lyrics for a specific video ID with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of ApiResponse (TranslatedLyricsListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TranslatedLyricsListResponse>> GetTranslatedLyricsByVideoIdAsyncWithHttpInfo (string videoId, int? limit = null, int? offset = null);
        /// <summary>
        /// Get Translated Lyrics by Video ID and Language
        /// </summary>
        /// <remarks>
        /// Fetches translated lyrics for a specific video ID and language code.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="language">Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;, &#x27;de&#x27;, &#x27;ja&#x27;)</param>
        /// <returns>Task of TranslatedLyricsListResponse</returns>
        System.Threading.Tasks.Task<TranslatedLyricsListResponse> GetTranslatedLyricsByVideoIdAndLanguageAsync (string videoId, string language);

        /// <summary>
        /// Get Translated Lyrics by Video ID and Language
        /// </summary>
        /// <remarks>
        /// Fetches translated lyrics for a specific video ID and language code.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="language">Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;, &#x27;de&#x27;, &#x27;ja&#x27;)</param>
        /// <returns>Task of ApiResponse (TranslatedLyricsListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TranslatedLyricsListResponse>> GetTranslatedLyricsByVideoIdAndLanguageAsyncWithHttpInfo (string videoId, string language);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class TranslationsApi : ITranslationsApi
    {
        private SimpMusic.Lyrics.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TranslationsApi(String basePath)
        {
            this.Configuration = new SimpMusic.Lyrics.Client.Configuration { BasePath = basePath };

            ExceptionFactory = SimpMusic.Lyrics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationsApi"/> class
        /// </summary>
        /// <returns></returns>
        public TranslationsApi()
        {
            this.Configuration = SimpMusic.Lyrics.Client.Configuration.Default;

            ExceptionFactory = SimpMusic.Lyrics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TranslationsApi(SimpMusic.Lyrics.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = SimpMusic.Lyrics.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = SimpMusic.Lyrics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SimpMusic.Lyrics.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SimpMusic.Lyrics.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create Translated Lyric Creates a new translated lyric entry. Requires HMAC authentication.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>CreateTranslatedLyricResponse</returns>
        public CreateTranslatedLyricResponse CreateTranslatedLyric (CreateTranslatedLyricRequest body)
        {
             ApiResponse<CreateTranslatedLyricResponse> localVarResponse = CreateTranslatedLyricWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create Translated Lyric Creates a new translated lyric entry. Requires HMAC authentication.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of CreateTranslatedLyricResponse</returns>
        public ApiResponse< CreateTranslatedLyricResponse > CreateTranslatedLyricWithHttpInfo (CreateTranslatedLyricRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling TranslationsApi->CreateTranslatedLyric");

            var localVarPath = "/v1/translated";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object? localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (hmacAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-HMAC")))
            {
                localVarHeaderParams["X-HMAC"] = this.Configuration.GetApiKeyWithPrefix("X-HMAC");
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateTranslatedLyric", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateTranslatedLyricResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (CreateTranslatedLyricResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateTranslatedLyricResponse)));
        }

        /// <summary>
        /// Create Translated Lyric Creates a new translated lyric entry. Requires HMAC authentication.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of CreateTranslatedLyricResponse</returns>
        public async System.Threading.Tasks.Task<CreateTranslatedLyricResponse> CreateTranslatedLyricAsync (CreateTranslatedLyricRequest body)
        {
             ApiResponse<CreateTranslatedLyricResponse> localVarResponse = await CreateTranslatedLyricAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create Translated Lyric Creates a new translated lyric entry. Requires HMAC authentication.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (CreateTranslatedLyricResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreateTranslatedLyricResponse>> CreateTranslatedLyricAsyncWithHttpInfo (CreateTranslatedLyricRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling TranslationsApi->CreateTranslatedLyric");

            var localVarPath = "/v1/translated";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object? localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (hmacAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-HMAC")))
            {
                localVarHeaderParams["X-HMAC"] = this.Configuration.GetApiKeyWithPrefix("X-HMAC");
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateTranslatedLyric", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateTranslatedLyricResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (CreateTranslatedLyricResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateTranslatedLyricResponse)));
        }

        /// <summary>
        /// Get Translated Lyrics by Video ID Fetches translated lyrics for a specific video ID with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>TranslatedLyricsListResponse</returns>
        public TranslatedLyricsListResponse GetTranslatedLyricsByVideoId (string videoId, int? limit = null, int? offset = null)
        {
             ApiResponse<TranslatedLyricsListResponse> localVarResponse = GetTranslatedLyricsByVideoIdWithHttpInfo(videoId, limit, offset);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Translated Lyrics by Video ID Fetches translated lyrics for a specific video ID with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>ApiResponse of TranslatedLyricsListResponse</returns>
        public ApiResponse< TranslatedLyricsListResponse > GetTranslatedLyricsByVideoIdWithHttpInfo (string videoId, int? limit = null, int? offset = null)
        {
            // verify the required parameter 'videoId' is set
            if (videoId == null)
                throw new ApiException(400, "Missing required parameter 'videoId' when calling TranslationsApi->GetTranslatedLyricsByVideoId");

            var localVarPath = "/v1/translated/{videoId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object? localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (videoId != null) localVarPathParams.Add("videoId", this.Configuration.ApiClient.ParameterToString(videoId)); // path parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTranslatedLyricsByVideoId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TranslatedLyricsListResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (TranslatedLyricsListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TranslatedLyricsListResponse)));
        }

        /// <summary>
        /// Get Translated Lyrics by Video ID Fetches translated lyrics for a specific video ID with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of TranslatedLyricsListResponse</returns>
        public async System.Threading.Tasks.Task<TranslatedLyricsListResponse> GetTranslatedLyricsByVideoIdAsync (string videoId, int? limit = null, int? offset = null)
        {
             ApiResponse<TranslatedLyricsListResponse> localVarResponse = await GetTranslatedLyricsByVideoIdAsyncWithHttpInfo(videoId, limit, offset);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Translated Lyrics by Video ID Fetches translated lyrics for a specific video ID with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of ApiResponse (TranslatedLyricsListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TranslatedLyricsListResponse>> GetTranslatedLyricsByVideoIdAsyncWithHttpInfo (string videoId, int? limit = null, int? offset = null)
        {
            // verify the required parameter 'videoId' is set
            if (videoId == null)
                throw new ApiException(400, "Missing required parameter 'videoId' when calling TranslationsApi->GetTranslatedLyricsByVideoId");

            var localVarPath = "/v1/translated/{videoId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object? localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (videoId != null) localVarPathParams.Add("videoId", this.Configuration.ApiClient.ParameterToString(videoId)); // path parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody!, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTranslatedLyricsByVideoId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TranslatedLyricsListResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (TranslatedLyricsListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TranslatedLyricsListResponse)));
        }

        /// <summary>
        /// Get Translated Lyrics by Video ID and Language Fetches translated lyrics for a specific video ID and language code.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="language">Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;, &#x27;de&#x27;, &#x27;ja&#x27;)</param>
        /// <returns>TranslatedLyricsListResponse</returns>
        public TranslatedLyricsListResponse GetTranslatedLyricsByVideoIdAndLanguage (string videoId, string language)
        {
             ApiResponse<TranslatedLyricsListResponse> localVarResponse = GetTranslatedLyricsByVideoIdAndLanguageWithHttpInfo(videoId, language);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Translated Lyrics by Video ID and Language Fetches translated lyrics for a specific video ID and language code.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="language">Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;, &#x27;de&#x27;, &#x27;ja&#x27;)</param>
        /// <returns>ApiResponse of TranslatedLyricsListResponse</returns>
        public ApiResponse< TranslatedLyricsListResponse > GetTranslatedLyricsByVideoIdAndLanguageWithHttpInfo (string videoId, string language)
        {
            // verify the required parameter 'videoId' is set
            if (videoId == null)
                throw new ApiException(400, "Missing required parameter 'videoId' when calling TranslationsApi->GetTranslatedLyricsByVideoIdAndLanguage");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling TranslationsApi->GetTranslatedLyricsByVideoIdAndLanguage");

            var localVarPath = "/v1/translated/{videoId}/{language}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object? localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (videoId != null) localVarPathParams.Add("videoId", this.Configuration.ApiClient.ParameterToString(videoId)); // path parameter
            if (language != null) localVarPathParams.Add("language", this.Configuration.ApiClient.ParameterToString(language)); // path parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTranslatedLyricsByVideoIdAndLanguage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TranslatedLyricsListResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (TranslatedLyricsListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TranslatedLyricsListResponse)));
        }

        /// <summary>
        /// Get Translated Lyrics by Video ID and Language Fetches translated lyrics for a specific video ID and language code.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="language">Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;, &#x27;de&#x27;, &#x27;ja&#x27;)</param>
        /// <returns>Task of TranslatedLyricsListResponse</returns>
        public async System.Threading.Tasks.Task<TranslatedLyricsListResponse> GetTranslatedLyricsByVideoIdAndLanguageAsync (string videoId, string language)
        {
             ApiResponse<TranslatedLyricsListResponse> localVarResponse = await GetTranslatedLyricsByVideoIdAndLanguageAsyncWithHttpInfo(videoId, language);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Translated Lyrics by Video ID and Language Fetches translated lyrics for a specific video ID and language code.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="videoId">YouTube video ID</param>
        /// <param name="language">Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;, &#x27;de&#x27;, &#x27;ja&#x27;)</param>
        /// <returns>Task of ApiResponse (TranslatedLyricsListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TranslatedLyricsListResponse>> GetTranslatedLyricsByVideoIdAndLanguageAsyncWithHttpInfo (string videoId, string language)
        {
            // verify the required parameter 'videoId' is set
            if (videoId == null)
                throw new ApiException(400, "Missing required parameter 'videoId' when calling TranslationsApi->GetTranslatedLyricsByVideoIdAndLanguage");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling TranslationsApi->GetTranslatedLyricsByVideoIdAndLanguage");

            var localVarPath = "/v1/translated/{videoId}/{language}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object? localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (videoId != null) localVarPathParams.Add("videoId", this.Configuration.ApiClient.ParameterToString(videoId)); // path parameter
            if (language != null) localVarPathParams.Add("language", this.Configuration.ApiClient.ParameterToString(language)); // path parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody!, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTranslatedLyricsByVideoIdAndLanguage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TranslatedLyricsListResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (TranslatedLyricsListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TranslatedLyricsListResponse)));
        }

    }
}
