/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using RestSharp;

namespace SimpMusic.Lyrics.Client
{
    /// <summary>
    /// A delegate to ExceptionFactory method
    /// </summary>
    /// <param name="methodName">Method name</param>
    /// <param name="response">Response</param>
    /// <returns>Exceptions</returns>
    public delegate Exception ExceptionFactory(string methodName, RestResponse response);
}
