/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Newtonsoft.Json.Converters;

namespace SimpMusic.Lyrics.Client
{
    /// <summary>
    /// Formatter for 'date' swagger formats ss defined by full-date - RFC3339
    /// see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types
    /// </summary>
    public class SwaggerDateConverter : IsoDateTimeConverter
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SwaggerDateConverter" /> class.
        /// </summary>
        public SwaggerDateConverter()
        {
            // full-date   = date-fullyear "-" date-month "-" date-mday
            DateTimeFormat = "yyyy-MM-dd";
        }
    }
}
