/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SimpMusic.Lyrics.Client.SwaggerDateConverter;
namespace SimpMusic.Lyrics.Client.Model
{
    /// <summary>
    /// CreateLyricRequest
    /// </summary>
    [DataContract]
        public partial class CreateLyricRequest :  IEquatable<CreateLyricRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLyricRequest" /> class.
        /// </summary>
        /// <param name="videoId">YouTube video ID (required).</param>
        /// <param name="songTitle">Title of the song (required).</param>
        /// <param name="artistName">Name of the artist (required).</param>
        /// <param name="albumName">Name of the album (optional).</param>
        /// <param name="durationSeconds">Duration of the song in seconds.</param>
        /// <param name="plainLyric">Plain text lyrics without timing information.</param>
        /// <param name="syncedLyrics">Synced lyrics in LRC format with line-level timing.</param>
        /// <param name="richSyncLyrics">Rich synced lyrics with word-level timing.</param>
        /// <param name="vote">Initial vote count (defaults to 0).</param>
        /// <param name="contributor">Name of the contributor.</param>
        /// <param name="contributorEmail">Email of the contributor.</param>
        public CreateLyricRequest(string videoId = default(string), string songTitle = default(string), string artistName = default(string), string albumName = default(string), int? durationSeconds = default(int?), string plainLyric = default(string), string syncedLyrics = default(string), string richSyncLyrics = default(string), int? vote = default(int?), string contributor = default(string), string contributorEmail = default(string))
        {
            // to ensure "videoId" is required (not null)
            if (videoId == null)
            {
                throw new InvalidDataException("videoId is a required property for CreateLyricRequest and cannot be null");
            }
            else
            {
                this.VideoId = videoId;
            }
            // to ensure "songTitle" is required (not null)
            if (songTitle == null)
            {
                throw new InvalidDataException("songTitle is a required property for CreateLyricRequest and cannot be null");
            }
            else
            {
                this.SongTitle = songTitle;
            }
            // to ensure "artistName" is required (not null)
            if (artistName == null)
            {
                throw new InvalidDataException("artistName is a required property for CreateLyricRequest and cannot be null");
            }
            else
            {
                this.ArtistName = artistName;
            }
            this.AlbumName = albumName;
            this.DurationSeconds = durationSeconds;
            this.PlainLyric = plainLyric;
            this.SyncedLyrics = syncedLyrics;
            this.RichSyncLyrics = richSyncLyrics;
            this.Vote = vote;
            this.Contributor = contributor;
            this.ContributorEmail = contributorEmail;
        }
        
        /// <summary>
        /// YouTube video ID
        /// </summary>
        /// <value>YouTube video ID</value>
        [DataMember(Name="videoId", EmitDefaultValue=false)]
        public string VideoId { get; set; }

        /// <summary>
        /// Title of the song
        /// </summary>
        /// <value>Title of the song</value>
        [DataMember(Name="songTitle", EmitDefaultValue=false)]
        public string SongTitle { get; set; }

        /// <summary>
        /// Name of the artist
        /// </summary>
        /// <value>Name of the artist</value>
        [DataMember(Name="artistName", EmitDefaultValue=false)]
        public string ArtistName { get; set; }

        /// <summary>
        /// Name of the album (optional)
        /// </summary>
        /// <value>Name of the album (optional)</value>
        [DataMember(Name="albumName", EmitDefaultValue=false)]
        public string AlbumName { get; set; }

        /// <summary>
        /// Duration of the song in seconds
        /// </summary>
        /// <value>Duration of the song in seconds</value>
        [DataMember(Name="durationSeconds", EmitDefaultValue=false)]
        public int? DurationSeconds { get; set; }

        /// <summary>
        /// Plain text lyrics without timing information
        /// </summary>
        /// <value>Plain text lyrics without timing information</value>
        [DataMember(Name="plainLyric", EmitDefaultValue=false)]
        public string PlainLyric { get; set; }

        /// <summary>
        /// Synced lyrics in LRC format with line-level timing
        /// </summary>
        /// <value>Synced lyrics in LRC format with line-level timing</value>
        [DataMember(Name="syncedLyrics", EmitDefaultValue=false)]
        public string SyncedLyrics { get; set; }

        /// <summary>
        /// Rich synced lyrics with word-level timing
        /// </summary>
        /// <value>Rich synced lyrics with word-level timing</value>
        [DataMember(Name="richSyncLyrics", EmitDefaultValue=false)]
        public string RichSyncLyrics { get; set; }

        /// <summary>
        /// Initial vote count (defaults to 0)
        /// </summary>
        /// <value>Initial vote count (defaults to 0)</value>
        [DataMember(Name="vote", EmitDefaultValue=false)]
        public int? Vote { get; set; }

        /// <summary>
        /// Name of the contributor
        /// </summary>
        /// <value>Name of the contributor</value>
        [DataMember(Name="contributor", EmitDefaultValue=false)]
        public string Contributor { get; set; }

        /// <summary>
        /// Email of the contributor
        /// </summary>
        /// <value>Email of the contributor</value>
        [DataMember(Name="contributorEmail", EmitDefaultValue=false)]
        public string ContributorEmail { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateLyricRequest {\n");
            sb.Append("  VideoId: ").Append(VideoId).Append("\n");
            sb.Append("  SongTitle: ").Append(SongTitle).Append("\n");
            sb.Append("  ArtistName: ").Append(ArtistName).Append("\n");
            sb.Append("  AlbumName: ").Append(AlbumName).Append("\n");
            sb.Append("  DurationSeconds: ").Append(DurationSeconds).Append("\n");
            sb.Append("  PlainLyric: ").Append(PlainLyric).Append("\n");
            sb.Append("  SyncedLyrics: ").Append(SyncedLyrics).Append("\n");
            sb.Append("  RichSyncLyrics: ").Append(RichSyncLyrics).Append("\n");
            sb.Append("  Vote: ").Append(Vote).Append("\n");
            sb.Append("  Contributor: ").Append(Contributor).Append("\n");
            sb.Append("  ContributorEmail: ").Append(ContributorEmail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateLyricRequest);
        }

        /// <summary>
        /// Returns true if CreateLyricRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateLyricRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateLyricRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.VideoId == input.VideoId ||
                    (this.VideoId != null &&
                    this.VideoId.Equals(input.VideoId))
                ) && 
                (
                    this.SongTitle == input.SongTitle ||
                    (this.SongTitle != null &&
                    this.SongTitle.Equals(input.SongTitle))
                ) && 
                (
                    this.ArtistName == input.ArtistName ||
                    (this.ArtistName != null &&
                    this.ArtistName.Equals(input.ArtistName))
                ) && 
                (
                    this.AlbumName == input.AlbumName ||
                    (this.AlbumName != null &&
                    this.AlbumName.Equals(input.AlbumName))
                ) && 
                (
                    this.DurationSeconds == input.DurationSeconds ||
                    (this.DurationSeconds != null &&
                    this.DurationSeconds.Equals(input.DurationSeconds))
                ) && 
                (
                    this.PlainLyric == input.PlainLyric ||
                    (this.PlainLyric != null &&
                    this.PlainLyric.Equals(input.PlainLyric))
                ) && 
                (
                    this.SyncedLyrics == input.SyncedLyrics ||
                    (this.SyncedLyrics != null &&
                    this.SyncedLyrics.Equals(input.SyncedLyrics))
                ) && 
                (
                    this.RichSyncLyrics == input.RichSyncLyrics ||
                    (this.RichSyncLyrics != null &&
                    this.RichSyncLyrics.Equals(input.RichSyncLyrics))
                ) && 
                (
                    this.Vote == input.Vote ||
                    (this.Vote != null &&
                    this.Vote.Equals(input.Vote))
                ) && 
                (
                    this.Contributor == input.Contributor ||
                    (this.Contributor != null &&
                    this.Contributor.Equals(input.Contributor))
                ) && 
                (
                    this.ContributorEmail == input.ContributorEmail ||
                    (this.ContributorEmail != null &&
                    this.ContributorEmail.Equals(input.ContributorEmail))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.VideoId != null)
                    hashCode = hashCode * 59 + this.VideoId.GetHashCode();
                if (this.SongTitle != null)
                    hashCode = hashCode * 59 + this.SongTitle.GetHashCode();
                if (this.ArtistName != null)
                    hashCode = hashCode * 59 + this.ArtistName.GetHashCode();
                if (this.AlbumName != null)
                    hashCode = hashCode * 59 + this.AlbumName.GetHashCode();
                if (this.DurationSeconds != null)
                    hashCode = hashCode * 59 + this.DurationSeconds.GetHashCode();
                if (this.PlainLyric != null)
                    hashCode = hashCode * 59 + this.PlainLyric.GetHashCode();
                if (this.SyncedLyrics != null)
                    hashCode = hashCode * 59 + this.SyncedLyrics.GetHashCode();
                if (this.RichSyncLyrics != null)
                    hashCode = hashCode * 59 + this.RichSyncLyrics.GetHashCode();
                if (this.Vote != null)
                    hashCode = hashCode * 59 + this.Vote.GetHashCode();
                if (this.Contributor != null)
                    hashCode = hashCode * 59 + this.Contributor.GetHashCode();
                if (this.ContributorEmail != null)
                    hashCode = hashCode * 59 + this.ContributorEmail.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
