/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SimpMusic.Lyrics.Client.SwaggerDateConverter;
namespace SimpMusic.Lyrics.Client.Model
{
    /// <summary>
    /// TranslatedLyric
    /// </summary>
    [DataContract]
        public partial class TranslatedLyric :  IEquatable<TranslatedLyric>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TranslatedLyric" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the translated lyric entry.</param>
        /// <param name="videoId">YouTube video ID.</param>
        /// <param name="translatedLyric">Translated lyric text.</param>
        /// <param name="language">Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;).</param>
        /// <param name="vote">Vote count for this translated lyric.</param>
        /// <param name="contributor">Name of the contributor who added this translation.</param>
        /// <param name="contributorEmail">Email of the contributor (may be hidden).</param>
        public TranslatedLyric(string id = default(string), string videoId = default(string), string translatedLyric = default(string), string language = default(string), int? vote = default(int?), string contributor = default(string), string contributorEmail = default(string))
        {
            this.Id = id;
            this.VideoId = videoId;
            this._TranslatedLyric = translatedLyric;
            this.Language = language;
            this.Vote = vote;
            this.Contributor = contributor;
            this.ContributorEmail = contributorEmail;
        }
        
        /// <summary>
        /// Unique identifier for the translated lyric entry
        /// </summary>
        /// <value>Unique identifier for the translated lyric entry</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// YouTube video ID
        /// </summary>
        /// <value>YouTube video ID</value>
        [DataMember(Name="videoId", EmitDefaultValue=false)]
        public string VideoId { get; set; }

        /// <summary>
        /// Translated lyric text
        /// </summary>
        /// <value>Translated lyric text</value>
        [DataMember(Name="translatedLyric", EmitDefaultValue=false)]
        public string _TranslatedLyric { get; set; }

        /// <summary>
        /// Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;)
        /// </summary>
        /// <value>Language code (e.g., &#x27;en&#x27;, &#x27;es&#x27;, &#x27;fr&#x27;)</value>
        [DataMember(Name="language", EmitDefaultValue=false)]
        public string Language { get; set; }

        /// <summary>
        /// Vote count for this translated lyric
        /// </summary>
        /// <value>Vote count for this translated lyric</value>
        [DataMember(Name="vote", EmitDefaultValue=false)]
        public int? Vote { get; set; }

        /// <summary>
        /// Name of the contributor who added this translation
        /// </summary>
        /// <value>Name of the contributor who added this translation</value>
        [DataMember(Name="contributor", EmitDefaultValue=false)]
        public string Contributor { get; set; }

        /// <summary>
        /// Email of the contributor (may be hidden)
        /// </summary>
        /// <value>Email of the contributor (may be hidden)</value>
        [DataMember(Name="contributorEmail", EmitDefaultValue=false)]
        public string ContributorEmail { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TranslatedLyric {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  VideoId: ").Append(VideoId).Append("\n");
            sb.Append("  _TranslatedLyric: ").Append(_TranslatedLyric).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Vote: ").Append(Vote).Append("\n");
            sb.Append("  Contributor: ").Append(Contributor).Append("\n");
            sb.Append("  ContributorEmail: ").Append(ContributorEmail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TranslatedLyric);
        }

        /// <summary>
        /// Returns true if TranslatedLyric instances are equal
        /// </summary>
        /// <param name="input">Instance of TranslatedLyric to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TranslatedLyric input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.VideoId == input.VideoId ||
                    (this.VideoId != null &&
                    this.VideoId.Equals(input.VideoId))
                ) && 
                (
                    this._TranslatedLyric == input._TranslatedLyric ||
                    (this._TranslatedLyric != null &&
                    this._TranslatedLyric.Equals(input._TranslatedLyric))
                ) && 
                (
                    this.Language == input.Language ||
                    (this.Language != null &&
                    this.Language.Equals(input.Language))
                ) && 
                (
                    this.Vote == input.Vote ||
                    (this.Vote != null &&
                    this.Vote.Equals(input.Vote))
                ) && 
                (
                    this.Contributor == input.Contributor ||
                    (this.Contributor != null &&
                    this.Contributor.Equals(input.Contributor))
                ) && 
                (
                    this.ContributorEmail == input.ContributorEmail ||
                    (this.ContributorEmail != null &&
                    this.ContributorEmail.Equals(input.ContributorEmail))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.VideoId != null)
                    hashCode = hashCode * 59 + this.VideoId.GetHashCode();
                if (this._TranslatedLyric != null)
                    hashCode = hashCode * 59 + this._TranslatedLyric.GetHashCode();
                if (this.Language != null)
                    hashCode = hashCode * 59 + this.Language.GetHashCode();
                if (this.Vote != null)
                    hashCode = hashCode * 59 + this.Vote.GetHashCode();
                if (this.Contributor != null)
                    hashCode = hashCode * 59 + this.Contributor.GetHashCode();
                if (this.ContributorEmail != null)
                    hashCode = hashCode * 59 + this.ContributorEmail.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
