/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SimpMusic.Lyrics.Client.Api;
using SimpMusic.Lyrics.Client.Model;
using SimpMusic.Lyrics.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SimpMusic.Lyrics.Tests.Test
{
    /// <summary>
    ///  Class for testing CreateLyricRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateLyricRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateLyricRequest
        //private CreateLyricRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateLyricRequest
            //instance = new CreateLyricRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateLyricRequest
        /// </summary>
        [Test]
        public void CreateLyricRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateLyricRequest
            //Assert.IsInstanceOfType<CreateLyricRequest> (instance, "variable 'instance' is a CreateLyricRequest");
        }


        /// <summary>
        /// Test the property 'VideoId'
        /// </summary>
        [Test]
        public void VideoIdTest()
        {
            // TODO unit test for the property 'VideoId'
        }
        /// <summary>
        /// Test the property 'SongTitle'
        /// </summary>
        [Test]
        public void SongTitleTest()
        {
            // TODO unit test for the property 'SongTitle'
        }
        /// <summary>
        /// Test the property 'ArtistName'
        /// </summary>
        [Test]
        public void ArtistNameTest()
        {
            // TODO unit test for the property 'ArtistName'
        }
        /// <summary>
        /// Test the property 'AlbumName'
        /// </summary>
        [Test]
        public void AlbumNameTest()
        {
            // TODO unit test for the property 'AlbumName'
        }
        /// <summary>
        /// Test the property 'DurationSeconds'
        /// </summary>
        [Test]
        public void DurationSecondsTest()
        {
            // TODO unit test for the property 'DurationSeconds'
        }
        /// <summary>
        /// Test the property 'PlainLyric'
        /// </summary>
        [Test]
        public void PlainLyricTest()
        {
            // TODO unit test for the property 'PlainLyric'
        }
        /// <summary>
        /// Test the property 'SyncedLyrics'
        /// </summary>
        [Test]
        public void SyncedLyricsTest()
        {
            // TODO unit test for the property 'SyncedLyrics'
        }
        /// <summary>
        /// Test the property 'RichSyncLyrics'
        /// </summary>
        [Test]
        public void RichSyncLyricsTest()
        {
            // TODO unit test for the property 'RichSyncLyrics'
        }
        /// <summary>
        /// Test the property 'Vote'
        /// </summary>
        [Test]
        public void VoteTest()
        {
            // TODO unit test for the property 'Vote'
        }
        /// <summary>
        /// Test the property 'Contributor'
        /// </summary>
        [Test]
        public void ContributorTest()
        {
            // TODO unit test for the property 'Contributor'
        }
        /// <summary>
        /// Test the property 'ContributorEmail'
        /// </summary>
        [Test]
        public void ContributorEmailTest()
        {
            // TODO unit test for the property 'ContributorEmail'
        }

    }

}
