/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SimpMusic.Lyrics.Client.Api;
using SimpMusic.Lyrics.Client.Model;
using SimpMusic.Lyrics.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SimpMusic.Lyrics.Tests
{
    /// <summary>
    ///  Class for testing CreateLyricResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateLyricResponseTests
    {
        // TODO uncomment below to declare an instance variable for CreateLyricResponse
        //private CreateLyricResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateLyricResponse
            //instance = new CreateLyricResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateLyricResponse
        /// </summary>
        [Test]
        public void CreateLyricResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateLyricResponse
            //Assert.IsInstanceOfType<CreateLyricResponse> (instance, "variable 'instance' is a CreateLyricResponse");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

    }

}
