/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SimpMusic.Lyrics.Client.Api;
using SimpMusic.Lyrics.Client.Model;
using SimpMusic.Lyrics.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SimpMusic.Lyrics.Tests.Test
{
    /// <summary>
    ///  Class for testing TranslatedLyric
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TranslatedLyricTests
    {
        // TODO uncomment below to declare an instance variable for TranslatedLyric
        //private TranslatedLyric instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TranslatedLyric
            //instance = new TranslatedLyric();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TranslatedLyric
        /// </summary>
        [Test]
        public void TranslatedLyricInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TranslatedLyric
            //Assert.IsInstanceOfType<TranslatedLyric> (instance, "variable 'instance' is a TranslatedLyric");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'VideoId'
        /// </summary>
        [Test]
        public void VideoIdTest()
        {
            // TODO unit test for the property 'VideoId'
        }
        /// <summary>
        /// Test the property '_TranslatedLyric'
        /// </summary>
        [Test]
        public void _TranslatedLyricTest()
        {
            // TODO unit test for the property '_TranslatedLyric'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Vote'
        /// </summary>
        [Test]
        public void VoteTest()
        {
            // TODO unit test for the property 'Vote'
        }
        /// <summary>
        /// Test the property 'Contributor'
        /// </summary>
        [Test]
        public void ContributorTest()
        {
            // TODO unit test for the property 'Contributor'
        }
        /// <summary>
        /// Test the property 'ContributorEmail'
        /// </summary>
        [Test]
        public void ContributorEmailTest()
        {
            // TODO unit test for the property 'ContributorEmail'
        }

    }

}
