/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using SimpMusic.Lyrics.Client;
using SimpMusic.Lyrics.Client.Model;

namespace SimpMusic.Lyrics.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ISearchApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Search Lyrics
        /// </summary>
        /// <remarks>
        /// Performs a general search across lyrics content with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Search query string</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>LyricsListResponse</returns>
        LyricsListResponse SearchLyrics (string q, int? limit = null, int? offset = null);

        /// <summary>
        /// Search Lyrics
        /// </summary>
        /// <remarks>
        /// Performs a general search across lyrics content with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Search query string</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>ApiResponse of LyricsListResponse</returns>
        ApiResponse<LyricsListResponse> SearchLyricsWithHttpInfo (string q, int? limit = null, int? offset = null);
        /// <summary>
        /// Search Lyrics by Artist
        /// </summary>
        /// <remarks>
        /// Searches for lyrics by artist name with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="artist">Artist name to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>LyricsListResponse</returns>
        LyricsListResponse SearchLyricsByArtist (string artist, int? limit = null, int? offset = null);

        /// <summary>
        /// Search Lyrics by Artist
        /// </summary>
        /// <remarks>
        /// Searches for lyrics by artist name with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="artist">Artist name to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>ApiResponse of LyricsListResponse</returns>
        ApiResponse<LyricsListResponse> SearchLyricsByArtistWithHttpInfo (string artist, int? limit = null, int? offset = null);
        /// <summary>
        /// Search Lyrics by Song Title
        /// </summary>
        /// <remarks>
        /// Searches for lyrics by song title with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="title">Song title to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>LyricsListResponse</returns>
        LyricsListResponse SearchLyricsByTitle (string title, int? limit = null, int? offset = null);

        /// <summary>
        /// Search Lyrics by Song Title
        /// </summary>
        /// <remarks>
        /// Searches for lyrics by song title with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="title">Song title to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>ApiResponse of LyricsListResponse</returns>
        ApiResponse<LyricsListResponse> SearchLyricsByTitleWithHttpInfo (string title, int? limit = null, int? offset = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Search Lyrics
        /// </summary>
        /// <remarks>
        /// Performs a general search across lyrics content with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Search query string</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of LyricsListResponse</returns>
        System.Threading.Tasks.Task<LyricsListResponse> SearchLyricsAsync (string q, int? limit = null, int? offset = null);

        /// <summary>
        /// Search Lyrics
        /// </summary>
        /// <remarks>
        /// Performs a general search across lyrics content with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Search query string</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of ApiResponse (LyricsListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LyricsListResponse>> SearchLyricsAsyncWithHttpInfo (string q, int? limit = null, int? offset = null);
        /// <summary>
        /// Search Lyrics by Artist
        /// </summary>
        /// <remarks>
        /// Searches for lyrics by artist name with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="artist">Artist name to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of LyricsListResponse</returns>
        System.Threading.Tasks.Task<LyricsListResponse> SearchLyricsByArtistAsync (string artist, int? limit = null, int? offset = null);

        /// <summary>
        /// Search Lyrics by Artist
        /// </summary>
        /// <remarks>
        /// Searches for lyrics by artist name with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="artist">Artist name to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of ApiResponse (LyricsListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LyricsListResponse>> SearchLyricsByArtistAsyncWithHttpInfo (string artist, int? limit = null, int? offset = null);
        /// <summary>
        /// Search Lyrics by Song Title
        /// </summary>
        /// <remarks>
        /// Searches for lyrics by song title with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="title">Song title to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of LyricsListResponse</returns>
        System.Threading.Tasks.Task<LyricsListResponse> SearchLyricsByTitleAsync (string title, int? limit = null, int? offset = null);

        /// <summary>
        /// Search Lyrics by Song Title
        /// </summary>
        /// <remarks>
        /// Searches for lyrics by song title with optional pagination using limit and offset parameters.
        /// </remarks>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="title">Song title to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of ApiResponse (LyricsListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LyricsListResponse>> SearchLyricsByTitleAsyncWithHttpInfo (string title, int? limit = null, int? offset = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class SearchApi : ISearchApi
    {
        private SimpMusic.Lyrics.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SearchApi(String basePath)
        {
            this.Configuration = new SimpMusic.Lyrics.Client.Configuration { BasePath = basePath };

            ExceptionFactory = SimpMusic.Lyrics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class
        /// </summary>
        /// <returns></returns>
        public SearchApi()
        {
            this.Configuration = SimpMusic.Lyrics.Client.Configuration.Default;

            ExceptionFactory = SimpMusic.Lyrics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SearchApi(SimpMusic.Lyrics.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = SimpMusic.Lyrics.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = SimpMusic.Lyrics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SimpMusic.Lyrics.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SimpMusic.Lyrics.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Search Lyrics Performs a general search across lyrics content with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Search query string</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>LyricsListResponse</returns>
        public LyricsListResponse SearchLyrics (string q, int? limit = null, int? offset = null)
        {
             ApiResponse<LyricsListResponse> localVarResponse = SearchLyricsWithHttpInfo(q, limit, offset);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Search Lyrics Performs a general search across lyrics content with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Search query string</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>ApiResponse of LyricsListResponse</returns>
        public ApiResponse< LyricsListResponse > SearchLyricsWithHttpInfo (string q, int? limit = null, int? offset = null)
        {
            // verify the required parameter 'q' is set
            if (q == null)
                throw new ApiException(400, "Missing required parameter 'q' when calling SearchApi->SearchLyrics");

            var localVarPath = "/v1/search";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (q != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "q", q)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SearchLyrics", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LyricsListResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (LyricsListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LyricsListResponse)));
        }

        /// <summary>
        /// Search Lyrics Performs a general search across lyrics content with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Search query string</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of LyricsListResponse</returns>
        public async System.Threading.Tasks.Task<LyricsListResponse> SearchLyricsAsync (string q, int? limit = null, int? offset = null)
        {
             ApiResponse<LyricsListResponse> localVarResponse = await SearchLyricsAsyncWithHttpInfo(q, limit, offset);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Search Lyrics Performs a general search across lyrics content with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Search query string</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of ApiResponse (LyricsListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LyricsListResponse>> SearchLyricsAsyncWithHttpInfo (string q, int? limit = null, int? offset = null)
        {
            // verify the required parameter 'q' is set
            if (q == null)
                throw new ApiException(400, "Missing required parameter 'q' when calling SearchApi->SearchLyrics");

            var localVarPath = "/v1/search";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (q != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "q", q)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody!, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SearchLyrics", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LyricsListResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (LyricsListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LyricsListResponse)));
        }

        /// <summary>
        /// Search Lyrics by Artist Searches for lyrics by artist name with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="artist">Artist name to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>LyricsListResponse</returns>
        public LyricsListResponse SearchLyricsByArtist (string artist, int? limit = null, int? offset = null)
        {
             ApiResponse<LyricsListResponse> localVarResponse = SearchLyricsByArtistWithHttpInfo(artist, limit, offset);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Search Lyrics by Artist Searches for lyrics by artist name with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="artist">Artist name to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>ApiResponse of LyricsListResponse</returns>
        public ApiResponse< LyricsListResponse > SearchLyricsByArtistWithHttpInfo (string artist, int? limit = null, int? offset = null)
        {
            // verify the required parameter 'artist' is set
            if (artist == null)
                throw new ApiException(400, "Missing required parameter 'artist' when calling SearchApi->SearchLyricsByArtist");

            var localVarPath = "/v1/search/artist";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (artist != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "artist", artist)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SearchLyricsByArtist", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LyricsListResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (LyricsListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LyricsListResponse)));
        }

        /// <summary>
        /// Search Lyrics by Artist Searches for lyrics by artist name with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="artist">Artist name to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of LyricsListResponse</returns>
        public async System.Threading.Tasks.Task<LyricsListResponse> SearchLyricsByArtistAsync (string artist, int? limit = null, int? offset = null)
        {
             ApiResponse<LyricsListResponse> localVarResponse = await SearchLyricsByArtistAsyncWithHttpInfo(artist, limit, offset);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Search Lyrics by Artist Searches for lyrics by artist name with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="artist">Artist name to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of ApiResponse (LyricsListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LyricsListResponse>> SearchLyricsByArtistAsyncWithHttpInfo (string artist, int? limit = null, int? offset = null)
        {
            // verify the required parameter 'artist' is set
            if (artist == null)
                throw new ApiException(400, "Missing required parameter 'artist' when calling SearchApi->SearchLyricsByArtist");

            var localVarPath = "/v1/search/artist";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (artist != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "artist", artist)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody!, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SearchLyricsByArtist", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LyricsListResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (LyricsListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LyricsListResponse)));
        }

        /// <summary>
        /// Search Lyrics by Song Title Searches for lyrics by song title with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="title">Song title to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>LyricsListResponse</returns>
        public LyricsListResponse SearchLyricsByTitle (string title, int? limit = null, int? offset = null)
        {
             ApiResponse<LyricsListResponse> localVarResponse = SearchLyricsByTitleWithHttpInfo(title, limit, offset);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Search Lyrics by Song Title Searches for lyrics by song title with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="title">Song title to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>ApiResponse of LyricsListResponse</returns>
        public ApiResponse< LyricsListResponse > SearchLyricsByTitleWithHttpInfo (string title, int? limit = null, int? offset = null)
        {
            // verify the required parameter 'title' is set
            if (title == null)
                throw new ApiException(400, "Missing required parameter 'title' when calling SearchApi->SearchLyricsByTitle");

            var localVarPath = "/v1/search/title";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (title != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "title", title)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SearchLyricsByTitle", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LyricsListResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (LyricsListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LyricsListResponse)));
        }

        /// <summary>
        /// Search Lyrics by Song Title Searches for lyrics by song title with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="title">Song title to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of LyricsListResponse</returns>
        public async System.Threading.Tasks.Task<LyricsListResponse> SearchLyricsByTitleAsync (string title, int? limit = null, int? offset = null)
        {
             ApiResponse<LyricsListResponse> localVarResponse = await SearchLyricsByTitleAsyncWithHttpInfo(title, limit, offset);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Search Lyrics by Song Title Searches for lyrics by song title with optional pagination using limit and offset parameters.
        /// </summary>
        /// <exception cref="SimpMusic.Lyrics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="title">Song title to search for</param>
        /// <param name="limit">Maximum number of results to return (optional)</param>
        /// <param name="offset">Number of results to skip (optional)</param>
        /// <returns>Task of ApiResponse (LyricsListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LyricsListResponse>> SearchLyricsByTitleAsyncWithHttpInfo (string title, int? limit = null, int? offset = null)
        {
            // verify the required parameter 'title' is set
            if (title == null)
                throw new ApiException(400, "Missing required parameter 'title' when calling SearchApi->SearchLyricsByTitle");

            var localVarPath = "/v1/search/title";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (title != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "title", title)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody!, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SearchLyricsByTitle", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LyricsListResponse>(localVarStatusCode,
                localVarResponse.Headers.GroupBy(x => x.Name).ToDictionary(g => g.Key, g => string.Join(",", g.SelectMany(x => x.Value))),
                (LyricsListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LyricsListResponse)));
        }

    }
}
