/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SimpMusic.Lyrics.Client.Client;
using SimpMusic.Lyrics.Client.Api;
using SimpMusic.Lyrics.Client.Model;

namespace SimpMusic.Lyrics.Tests.Test
{
    /// <summary>
    ///  Class for testing LyricsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LyricsApiTests
    {
        private LyricsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LyricsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LyricsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LyricsApi
            //Assert.IsInstanceOfType(typeof(LyricsApi), instance, "instance is a LyricsApi");
        }

        /// <summary>
        /// Test CreateLyric
        /// </summary>
        [Test]
        public void CreateLyricTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateLyricRequest body = null;
            //var response = instance.CreateLyric(body);
            //Assert.IsInstanceOf<CreateLyricResponse> (response, "response is CreateLyricResponse");
        }
        /// <summary>
        /// Test GetLyricsByVideoId
        /// </summary>
        [Test]
        public void GetLyricsByVideoIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string videoId = null;
            //int? limit = null;
            //int? offset = null;
            //var response = instance.GetLyricsByVideoId(videoId, limit, offset);
            //Assert.IsInstanceOf<LyricsResponse> (response, "response is LyricsResponse");
        }
    }

}
