/* 
 * SimpMusic Lyrics API
 *
 * API for accessing lyrics and translations for songs. Supports synced lyrics, plain lyrics, and community-contributed translations.  **Rate Limiting:** - 30 requests per minute per IP address - Applies to all API endpoints - Rate limit headers are included in all responses - When limit is exceeded, returns HTTP 429 (Too Many Requests) with Retry-After header
 *
 * OpenAPI spec version: v1
 * Contact: support@simpmusic.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SimpMusic.Lyrics.Client.Client;
using SimpMusic.Lyrics.Client.Api;
using SimpMusic.Lyrics.Client.Model;

namespace SimpMusic.Lyrics.Tests
{
    /// <summary>
    ///  Class for testing TranslationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TranslationsApiTests
    {
        private TranslationsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TranslationsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TranslationsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TranslationsApi
            //Assert.IsInstanceOfType(typeof(TranslationsApi), instance, "instance is a TranslationsApi");
        }

        /// <summary>
        /// Test CreateTranslatedLyric
        /// </summary>
        [Test]
        public void CreateTranslatedLyricTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateTranslatedLyricRequest body = null;
            //var response = instance.CreateTranslatedLyric(body);
            //Assert.IsInstanceOf<CreateTranslatedLyricResponse> (response, "response is CreateTranslatedLyricResponse");
        }
        /// <summary>
        /// Test GetTranslatedLyricsByVideoId
        /// </summary>
        [Test]
        public void GetTranslatedLyricsByVideoIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string videoId = null;
            //int? limit = null;
            //int? offset = null;
            //var response = instance.GetTranslatedLyricsByVideoId(videoId, limit, offset);
            //Assert.IsInstanceOf<TranslatedLyricsListResponse> (response, "response is TranslatedLyricsListResponse");
        }
        /// <summary>
        /// Test GetTranslatedLyricsByVideoIdAndLanguage
        /// </summary>
        [Test]
        public void GetTranslatedLyricsByVideoIdAndLanguageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string videoId = null;
            //string language = null;
            //var response = instance.GetTranslatedLyricsByVideoIdAndLanguage(videoId, language);
            //Assert.IsInstanceOf<TranslatedLyricsListResponse> (response, "response is TranslatedLyricsListResponse");
        }
    }

}
